#!/usr/bin/env bash

set -e

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source $SCRIPT_DIR/_kubectl-enonic-common

ns=$(get_namespace)
dp=$(get_deployment $ns)
pd=$(get_pod $ns $dp)

kubectl -n $ns logs -c exp -f $pd
