#!/usr/bin/env bash

set -e

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source $SCRIPT_DIR/_kubectl-enonic-common

cat <<EOF
Run commands agains the Enonic XP running in K8s

Usage:
  kubectl enonic xp [command]

Available Commands:
  admin         Print su password and port forward to XP pod
  exec          Exec into a XP container
  forward       Port forward to a XP pod
  idproviders   List available idproviders
  logs          Show XP logs
  routes        List available internal routes
  snapshots     List available snapshots
  supass        Show XP su password
  projects      List available projects
  webapps       List available webapps
EOF
