#!/usr/bin/env bash

set -e

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source $SCRIPT_DIR/_kubectl-enonic-common

ns=$(get_namespace)
[ -z "$ns" ] && (echo "No namespace selected!" 1>&2; exit 1;)

dp=$(get_deployment $ns)
[ -z "$dp" ] && (echo "No deployment selected!" 1>&2; exit 1;)

ng=$(get_nodegroup $ns $dp)
[ -z "$ng" ] && (echo "No node group selected!" 1>&2; exit 1;)

kubectl_get /xp7/$ns/$dp/$ng/mgmt/content/projects/list | jq -r .
