#!/usr/bin/env bash

set -e

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source $SCRIPT_DIR/_kubectl-enonic-common

ns=$(get_namespace)
dp=$(get_deployment $ns)
ng=$(get_nodegroup $ns $dp)

kubectl_get /xp7/$ns/$dp/$ng/mgmt/repo/snapshot/list | jq
