#!/usr/bin/env bash

set -e

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source $SCRIPT_DIR/_kubectl-enonic-common

ns=$(get_namespace)
[ -z "$ns" ] && (echo "No namespace selected!" 1>&2; exit 1;)

kubectl -n $ns get secret su -o go-template="{{ .data.pass | base64decode }}"
