{{ if $.Values.backup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xp-backup-sa
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "20"
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xp-backup-role
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "30"
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
  - apiGroups:
      - "*"
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - "*"
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xp-backup-role-bindings
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "40"
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xp-backup-role
subjects:
  - kind: ServiceAccount
    name: xp-backup-sa
    namespace: {{ $.Values.deployment.namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: xp-backup-sa-secret
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "60"
    kubernetes.io/service-account.name: xp-backup-sa
type: kubernetes.io/service-account-token
{{- end }}
