# Setup SA for nodes
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xp-node-sa
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "20"
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xp-node-role
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "30"
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
{{- if $.Values.settings.hzApiDiscovery }}
  # For HZ api discovery
  - apiGroups:
      - "*"
    resources:
      - endpoints
      - pods
      - services
    verbs:
      - get
      - list
{{- else }}
  # For preStopHook
  - apiGroups:
      - '*'
    resources:
      - endpoints
    verbs:
      - get
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xp-node-role-bindings
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "40"
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xp-node-role
subjects:
  - kind: ServiceAccount
    name: xp-node-sa
    namespace: {{ $.Values.deployment.namespace }}
# Cluster roles for HZ
{{- if and $.Values.settings.hzApiDiscovery $.Values.deployment.clustered }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Values.deployment.namespace }}-hazelcast
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "30"
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
  - apiGroups:
      - "*"
    resources:
      - nodes
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Values.deployment.namespace }}-hazelcast
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "40"
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Values.deployment.namespace }}-hazelcast
subjects:
  - kind: ServiceAccount
    name: xp-node-sa
    namespace: {{ $.Values.deployment.namespace }}
{{- end }}
