# Setup ES / Hazelcast discovery
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.discoveryService }}
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "100"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  sessionAffinity: None
  selector:
    {{ $.Values.labelKeys.deployment }}: {{ $.Values.deployment.name }}
  ports:
    - name: hazelcast
      port: 5701
      targetPort: 5701
      protocol: TCP
    - name: es
      port: 9300
      targetPort: 9300
      protocol: TCP
---

# Setup service that points to all nodes in the cluster
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.allNodesKey }}
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "100"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{- with .Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None
  selector:
    {{ $.Values.labelKeys.deployment }}: {{ $.Values.deployment.name }}
  ports:
    - name: xp-metrics
      port: 2609
      targetPort: 2609
      protocol: TCP
    - name: xp-management
      port: 4848
      targetPort: 4848
      protocol: TCP
    - name: xp-main
      port: 8080
      targetPort: 8080
      protocol: TCP
