# Setup service pointing to each nodeGroup
{{- range $nodeGroup := .Values.deployment.spec.nodeGroups }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $nodeGroup.name }}
  namespace: {{ $.Values.deployment.namespace }}
  annotations:
    {{ $.Values.annotationKeys.applyPriority }}: "100"
  labels:
    {{ $.Values.labelKeys.managed }}: true
    {{ $.Values.labelKeys.nodeGroup }}: {{ $nodeGroup.name }}
    {{- with $.Values.defaultLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ownerReferences:
    {{- with $.Values.ownerReferences }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None
  selector:
    {{ $.Values.labelKeys.nodeGroup }}: {{ $nodeGroup.name }}
    {{ $.Values.labelKeys.deployment }}: {{ $.Values.deployment.name }}
  ports:
    - name: xp-metrics
      port: 2609
      targetPort: 2609
      protocol: TCP
    - name: xp-management
      port: 4848
      targetPort: 4848
      protocol: TCP
    - name: xp-main
      port: 8080
      targetPort: 8080
      protocol: TCP
---
{{- end }}
