apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: xp7apps.enonic.cloud
spec:
  group: enonic.cloud
  scope: Namespaced
  preserveUnknownFields: false
  names:
    kind: Xp7App
    singular: xp7app
    plural: xp7apps
  conversion:
    strategy: None # Schemas are the same
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                enabled:
                  type: boolean
                  nullable: true
                url:
                  type: string
                sha512:
                  type: string
                  nullable: true
            status:
              type: object
              nullable: true
              properties:
                state:
                  type: string
                  enum : ["ERROR", "PENDING", "STOPPED", "RUNNING"]
                message:
                  type: string
                fields:
                  type: object
                  properties:
                    appInfo:
                      type: object
                      nullable: true
                      properties:
                        description:
                          type: string
                          nullable: true
                        displayName:
                          type: string
                          nullable: true
                        key:
                          type: string
                          nullable: true
                        modifiedTime:
                          type: string
                          nullable: true
                        state:
                          type: string
                          nullable: true
                        url:
                          type: string
                          nullable: true
                        vendorName:
                          type: string
                          nullable: true
                        vendorUrl:
                          type: string
                          nullable: true
                        version:
                          type: string
                          nullable: true
      additionalPrinterColumns:
        - name: Key
          type: string
          description: Key
          jsonPath: .status.fields.appInfo.key
        - name: Version
          type: string
          description: Version
          jsonPath: .status.fields.appInfo.version
        - name: State
          type: string
          description: State
          jsonPath: .status.state
        - name: Msg
          type: string
          description: Message
          jsonPath: .status.message
