apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: domains.enonic.cloud
spec:
  group: enonic.cloud
  scope: Cluster
  preserveUnknownFields: false
  names:
    kind: Domain
    singular: domain
    plural: domains
  conversion:
    strategy: None # Schemas are the same
  versions:
    - name: v1alpha2
      served: true
      storage: false
      deprecated: true
      deprecationWarning: "enonic.cloud/v1alpha2 Domain is deprecated; Use v1."
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                host:
                  type: string
                dnsRecord:
                  type: boolean
                dnsTTL:
                  type: integer
                  nullable: true
                cdn:
                  type: boolean
                  nullable: true
                certificate:
                  type: object
                  nullable: true
                  properties:
                    authority:
                      type: string
                      enum: ["selfSigned", "letsEncrypt", "letsEncryptStaging", "clusterIssuer", "custom"]
                    identifier:
                      type: string
                      nullable: true
            status:
              type: object
              nullable: true
              properties:
                state:
                  type: string
                  enum: ["ERROR", "PENDING", "READY"]
                message:
                  type: string
                fields:
                  type: object
                  properties:
                    publicIps:
                      type: array
                      items:
                        type: string
                    dnsRecordCreated:
                      type: boolean
      additionalPrinterColumns:
        - name: Host
          type: string
          description: Host
          jsonPath: .spec.host
        - name: CDN
          type: string
          description: CDN
          jsonPath: .spec.cdn
        - name: CERT
          type: string
          description: Certificate Issuer
          jsonPath: .spec.certificate.authority
        - name: DNS
          type: string
          description: DNS Configured
          jsonPath: .status.fields.dnsRecordCreated
        - name: IP
          type: string
          description: Public IPs
          jsonPath: .status.fields.publicIps[*]
        - name: State
          type: string
          description: State
          jsonPath: .status.state
        - name: Msg
          type: string
          description: Message
          jsonPath: .status.message
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                host:
                  type: string
                dnsRecord:
                  type: boolean
                dnsTTL:
                  type: integer
                  nullable: true
                cdn:
                  type: boolean
                  nullable: true
                certificate:
                  type: object
                  nullable: true
                  properties:
                    authority:
                      type: string
                      enum: ["selfSigned", "letsEncrypt", "letsEncryptStaging", "clusterIssuer", "custom"]
                    identifier:
                      type: string
                      nullable: true
            status:
              type: object
              nullable: true
              properties:
                state:
                  type: string
                  enum: ["ERROR", "PENDING", "READY"]
                message:
                  type: string
                fields:
                  type: object
                  properties:
                    publicIps:
                      type: array
                      items:
                        type: string
                    dnsRecordCreated:
                      type: boolean
      additionalPrinterColumns:
        - name: Host
          type: string
          description: Host
          jsonPath: .spec.host
        - name: CDN
          type: string
          description: CDN
          jsonPath: .spec.cdn
        - name: CERT
          type: string
          description: Certificate Issuer
          jsonPath: .spec.certificate.authority
        - name: DNS
          type: string
          description: DNS Configured
          jsonPath: .status.fields.dnsRecordCreated
        - name: IP
          type: string
          description: Public IPs
          jsonPath: .status.fields.publicIps[*]
        - name: State
          type: string
          description: State
          jsonPath: .status.state
        - name: Msg
          type: string
          description: Message
          jsonPath: .status.message
