{{- if not .Values.onlyDeployCrds }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
data:
  {{- range $n, $v := .Values.secrets }}
  {{ $n }}: {{ $v | b64enc }}
  {{- end }}
---
{{- end }}