= Kubernetes Operator for Enonic XP
:toc: right
:imagesdir: images

The Enonic XP Kubernetes Operator is a piece of software runs on top of Kubernetes to help you manage your XP deployments. It builds on the https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[operator pattern] provided by Kubernetes.

== Motivation

Creating a simple XP deployment is quite easy, but it quickly gets more complicated when you try to create production grade clusters. Add on top the complexity of how Kubernetes works and you quickly can get into trouble. The operator removes that complexity for you, and makes it easy to create and manage complex deployments with ease.

== Usage

Take a look at the <<usage#,usage>> section see how to use the operator.

== Installation

Before you can start using the operator you have to:

* Have a running Kubernetes cluster, version `1.19+`. If you need to setup a local test environment, you can look at our <<minikube#,minikube>> guide.
* Install the operator according to the <<installation#,installation>> guide.

== Supported XP versions

NOTE: The operator only supports Enonic XP `v7.13.0` and newer.
