= Installation
:toc: right
:imagesdir: images

This section covers the installation and testing of the Enonic XP Kubernetes Operator.

== Prerequisites

Kubernetes:: A running Kubernetes cluster version `1.27+`. The k8s cluster can be on-premise or any cloud service provider. The only thing that differs depending on the type of k8s clusters is which storage class to use.
+
We have prepared documentation for setting up managed clusters using <<google#, Google>>, <<azure, Azure>> and <<amazon#, Amazon>>.

Kubectl:: Is the Kubernetes command-line tool, kubectl, allows you to run commands against Kubernetes clusters. Download it from https://kubernetes.io/docs/tasks/tools/install-kubectl/[kubernetes.io].

Helm:: Is a package manager for Kubernetes. Download it from https://helm.sh/docs/intro/install/[helm.sh].


== Create chart values file

Helm supports the use of chart files to customise the setup.

*Create a chart file* in a suitable location on your computer:

.values.yaml
[[values]]
[source,yaml]
----
config: |-
  # Set storage class names for volumes to be used by XP deployments.
  # The default storage class can be any storage class from your k8s cluster.
  # The shared storage class is used to run XP in cluster mode and it has to support ReadWriteMany!
  operator.charts.values.storage.default.storageClassName=standard
  operator.charts.values.storage.shared.storageClassName=nfs

  # Default CPU and RAM requests
  operator.charts.values.resources.cpu.defaultRequests=0.2
  operator.charts.values.resources.memory.defaultRequests=512Mi
----

[WARNING]
====
*Shared storage:* Make sure the `storage classes` are compatible with your Kubernetes cluster and cloud provider.

TIP: Amazon customers may use the `efs` storage class.

For `on-premises` k8s, or less expensive storage options we recommend <<nfs#,provision your own NFS storage>>.

For more details on compatibility, visit the <<storage-classes#, storage classes section>>.
====

More configuration options for the https://github.com/enonic/xp-operator/tree/master/helm[operator Helm chart]


== Installing the operator

Run the following command to install the operator on your cluster:

NOTE: *Namespaces* - We will be installing the XP operator in the default `kube-system` namespace, indicating that it is a vital system component, but you can also create your own if desired.

[source,terminal]
----
$ helm upgrade --install \
	--namespace kube-system \
	--values values.yaml \
	xp-operator \
	https://repo.enonic.com/helm/xp-operator/xp-operator-0.17.16.tgz

Release "xp-operator" does not exist. Installing it now.
NAME: xp-operator
LAST DEPLOYED: Wed Apr 27 17:18:38 2022
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
----

== Verify installation

. Find the name of the operator pod. The name of the pod will start with `xp-operator`:
+
[source,bash]
----
$ kubectl -n kube-system get pods

NAME                                                                READY   STATUS              RESTARTS   AGE
pod/event-exporter-gke-7bf6c99dcb-7dl56                             2/2     Running             0          16d
pod/kube-dns-5bfd847c64-2562d                                       4/4     Running             0          16d
pod/kube-proxy-gke-xp-test-gke-cluster-default-pool-d0fdd01c-jnfl   1/1     Running             0          16d
pod/l7-default-backend-d86c96845-j6m9b                              1/1     Running             0          16d
pod/xp-operator-684bb48cc5-bqjqc                                    0/1     ContainerCreating   0          9s
----
+
. Check the operator logs for errors. Logs for a working operator should look something like this:

[source,bash]
----
$ kubectl -n kube-system logs -f xp-operator-684bb48cc5-bqjqc

exec java -Doperator.charts.path=helm -Djava.util.logging.manager=org.jboss.logmanager.LogManager -javaagent:/opt/agent-bond/agent-bond.jar=jmx_exporter{{9779:/opt/agent-bond/jmx_exporter_config.yml}} -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/quarkus-run.jar
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2024-01-02 23:12:24,760 INFO  io.quarkus - java-operator 1.0.0 on JVM (powered by Quarkus 2.16.6.Final) started in 6.579s. Listening on: https://0.0.0.0:8443
2024-01-02 23:12:24,762 INFO  io.quarkus - Profile prod activated.
2024-01-02 23:12:24,764 INFO  io.quarkus - Installed features: [cdi, micrometer, rest-client, resteasy, resteasy-jackson, smallrye-context-propagation, vertx]
2024-01-02 23:12:25,808 INFO  com.eno.kub.ope.Operator - Adding listener 'OperatorIngress'
2024-01-02 23:12:25,889 INFO  com.eno.kub.ope.Operator - Adding listener 'OperatorXpClientCacheInvalidate'
2024-01-02 23:12:27,738 INFO  com.eno.kub.ope.Operator - Adding listener 'OperatorXp7DeploymentHelm'
2024-01-02 23:12:27,787 INFO  com.eno.kub.ope.Operator - Adding listener 'OperatorXp7AppStatusOnDeployments'
2024-01-02 23:12:27,799 INFO  com.eno.kub.ope.Operator - Adding listener 'OperatorDeleteAnnotation'
2024-01-02 23:12:27,803 INFO  com.eno.kub.ope.Operator - Adding schedule 'OperatorInformers' [delay: 16337, period: 30000]
2024-01-02 23:12:27,803 INFO  com.eno.kub.ope.Operator - Adding listener 'OperatorXp7ConfigStatus'
2024-01-02 23:12:27,804 INFO  com.eno.kub.ope.Operator - Adding listener 'OperatorIngressLabel'
2024-01-02 23:12:27,804 INFO  com.eno.kub.ope.Operator - Adding listener 'OperatorXp7AppInstaller'
2024-01-02 23:12:27,805 INFO  com.eno.kub.ope.Operator - Adding schedule 'OperatorXp7AppInstaller' [delay: 15212, period: 60000]
2024-01-02 23:12:27,805 INFO  com.eno.kub.ope.Operator - Adding listener 'OperatorXp7AppInstallerOnDeployments'
2024-01-02 23:12:27,806 INFO  com.eno.kub.ope.Operator - Adding listener 'OperatorConfigMapEvent'
2024-01-02 23:12:27,803 INFO  com.eno.kub.ope.Operator - Adding schedule 'OperatorConfigMapSync' [delay: 13252, period: 60000]
2024-01-02 23:12:27,804 INFO  com.eno.kub.ope.Operator - Adding schedule 'OperatorIngressLabel' [delay: 6622, period: 60000]
2024-01-02 23:12:27,806 INFO  com.eno.kub.ope.Operator - Adding listener 'OperatorXp7Config'
2024-01-02 23:12:27,807 INFO  com.eno.kub.ope.Operator - Adding listener 'OperatorIngressCertSync'
2024-01-02 23:12:27,807 INFO  com.eno.kub.ope.Operator - Adding schedule 'OperatorXp7ConfigSync' [delay: 10124, period: 60000]
2024-01-02 23:12:27,808 INFO  com.eno.kub.ope.Operator - Adding listener 'OperatorDomainCertSync'
2024-01-02 23:12:27,809 INFO  com.eno.kub.ope.Operator - Adding listener 'OperatorXp7AppStartStopper'
2024-01-02 23:12:27,809 INFO  com.eno.kub.ope.Operator - Adding schedule 'OperatorXp7AppStartStopper' [delay: 14806, period: 60000]
2024-01-02 23:12:27,809 INFO  com.eno.kub.ope.Operator - Adding listener 'OperatorXp7DeploymentStatus'
2024-01-02 23:12:27,810 INFO  com.eno.kub.ope.Operator - Adding schedule 'OperatorXp7DeploymentStatus' [delay: 4146, period: 60000]
2024-01-02 23:12:27,810 INFO  com.eno.kub.ope.Operator - Adding schedule 'OperatorXp7AppStatus' [delay: 19524, period: 60000]
2024-01-02 23:12:32,807 INFO  com.eno.kub.ope.Operator - Starting informers
----


== Test deployment

The best way of verifying that thangs are working, is by creating a basic xp7deployment.
The example below will create a namespace, a single-node XP7 server, pre-install selected applications, and configure an ingress.

WARNING: Remember to use a unique namespace per XP deployment. Never use the same namespace as the operator.

== Create xp7deployment

. Place this yaml file in a suitable location on your computer:
+
.simple.yaml
[source,yaml]
----
include::../kubernetes/example-simple.yaml[]
----
+
. Then run the following command to create the xp7deployment:
+
[source,bash]
----
kubectl apply -f single-xp7deployment-with-other-resources.yaml
----
+
.Output from a successful command
[source,terminal]
----
namespace/my-namespace created
xp7deployment.enonic.cloud/my-deployment created
xp7app.enonic.cloud/contentstudio created
xp7config.enonic.cloud/my-config created
ingress.networking.k8s.io/my-domain-com created
----
+
. Verify that the namespace exists, and that the pods have started:

[source,bash]
----
kubectl -n my-namespace get pods
----


=== XP Admin

With the XP running, we can try accessing the Admin - even without using the ingress.

. Get the `su` password by running this command:
+
[source,bash]
----
$ kubectl -n my-namespace get secret su -o go-template="{{ .data.pass | base64decode }}"
----
+
This will output the password string.
+
. Activate port forwarding
+
[source,bash]
----
$ kubectl -n my-namespace port-forward main-0 8080

Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
----
+
. Open http://localhost:8080[http://localhost:8080^] in your browser, and login with `su` and the password you obtained earlier.

TIP: Visit the <<usage#, operator usage section>> for more details.


=== Remove deployment

To remove the test deployment, run the following command:

.Use the same yaml as when creating the deployment
[source,bash]
----
kubectl delete -f simple.yaml
----

WARNING: Volumes are typically not deleted when you remove the deployment, so take care to remove them afterwards.


== Uninstall operator

NOTE: Don´t uninstall the xp-operator while there are remaining xp7Deployments on your cluster

To remove the XP operator from your Kubernetes cluster, run the following command:

[source,bash]
----
helm uninstall xp-operator
----


