= Minikube
:toc: right
:imagesdir: images

This section briefly describes how to install and set up minikube for testing the operator.

== Prerequisites

You need to have installed these programs on your computer:

Minikube:: Is local Kubernetes, focusing on making it easy to learn and develop for Kubernetes. Download it https://minikube.sigs.k8s.io/docs/start/[here].

Docker:: Is a container management platform. You can use other virtual machine or container managers with Minikube, but Docker is the most preferable Minikube https://minikube.sigs.k8s.io/docs/drivers/[driver] across all operating systems. Download it https://www.docker.com/products/docker-desktop/[here].

Kubectl:: Is the Kubernetes command-line tool, kubectl, allows you to run commands against Kubernetes clusters. Download it https://kubernetes.io/docs/tasks/tools/install-kubectl/[here].

== Setup

Once you have minikube working, it is quite easy to start a local cluster.

NOTE: You can run a cluster with less resources, but it won't be able to run any workloads. The amount of resources in this example won't let you run XP clusters. Feel free to add more juice if your machine can handle it.

NOTE: On Macbook clients with m1 chip, the virtualbox vm-driver is not supported and use "docker" instead of "virtualbox" as a vm-driver option.

[source,bash]
----
$ minikube start \
	--cpus=4 \
	--memory=16gb \
	--disk-size=10gb \
	--vm-driver=virtualbox \
	--kubernetes-version=v1.27.0

* Using the virtualbox driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=4, Memory=4096MB, Disk=16384MB) ...
* Preparing Kubernetes v1.27.0 on Docker 27.2.0 ...
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Verifying Kubernetes components...
* Enabled addons: storage-provisioner, default-storageclass
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
----

When your cluster is up, it is good to add the ingress controller to it to test load balancing:

[source,bash]
----
$ minikube addons enable ingress

* Verifying ingress addon...
* The 'ingress' addon is enabled
----

== Verify

Verify your setup by running:

[source,bash]
----
$ kubectl cluster-info

Kubernetes control plane is running at https://192.168.99.252:8443
KubeDNS is running at https://192.168.99.252:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
----

== Teardown

Once you are done with your cluster, you can delete the machine and all the data by running:

[source,bash]
----
$ minikube delete

* Deleting "minikube" in virtualbox ...
* Removed all traces of the "minikube" cluster.
----
