name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.7.0'

      - name: Build and test helm chart
        run: make build-helm

      - name: Build and test java-client and java-operator
        run: make build-java

  release:
    runs-on: ubuntu-latest

    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
          server-id: enonic
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.7.0'

      - name: Setup YQ
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: v4.25.1

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Assert versions
        run: |
          [ "${{ steps.tag.outputs.tag }}" == "$(./mvnw -f . help:evaluate -Dexpression=project.version -q -DforceStdout)" ] || (echo "version in pom.xml does not match tag"; exit 1)
          [ "${{ steps.tag.outputs.tag }}" == "$(./mvnw -f java-client help:evaluate -Dexpression=project.version -q -DforceStdout)" ] || (echo "version in java-client/pom.xml does not match tag"; exit 1)
          [ "${{ steps.tag.outputs.tag }}" == "$(./mvnw -f java-operator help:evaluate -Dexpression=project.version -q -DforceStdout)" ] || (echo "version in java-operator/pom.xml does not match tag"; exit 1)
          [ "${{ steps.tag.outputs.tag }}" == "$(yq '.appVersion' helm/Chart.yaml)" ] || (echo "appVersion in helm/Chart.yaml does not match tag"; exit 1)
          [ "${{ steps.tag.outputs.tag }}" == "$(yq '.version' helm/Chart.yaml)" ] || (echo "version in helm/Chart.yaml does not match tag"; exit 1)

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:qemu-v6.1.0-20
          platforms: all

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build java-client and java-operator
        run: ./mvnw clean package -DskipTests

      - name: Publish docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          pull: true
          no-cache: true
          push: true
          tags: "enonic/xp-operator:${{ steps.tag.outputs.tag }}"
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7

      - name: Publish helm chart
        working-directory: helm
        run: make publish
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASS: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Publish java-client
        run: ./mvnw --batch-mode -f java-client deploy
        env:
          MAVEN_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
